0 D tensor

In [3]:
import numpy as np
a = np.array(3)

In [4]:
a
a.ndim

0

1 D tensor 

In [9]:
arr = np.array([1, 2, 3])
arr 


array([1, 2, 3])

In [10]:
arr.ndim

1

2D Tensor

In [7]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
mat.ndim

2

3D tensor 

In [11]:
cube = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
cube

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [12]:
cube.ndim

3